spring:
  ai:
    vectorstore:
      chroma:
        client:
            host: 172.29.11.91
            port: 8010
        initialize-schema: true
    zhipuai:
      embedding:
        options:
          model: embedding-2
      chat:
        options:
          model: glm-4-air
          temperature: 0.7
      # 从启动参数中读取
      api-key: ${ZHIPUAI_API_KEY}